clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      elif: https://github.com/sethreader/sethrepo.theme.git

pipeline:
  build:
    image: chaosbunker/drone-hugo:latest
    settings:
      hugo_version: 0.56.1
      url: https://safe-universe.com
      validate: true
    volumes:
      - /root/dockerbunker/data/web/safe-universe.com:/drone/src/github.com/sethreader/safe-universe.com/public/
    commands:
      - hugo -v --cleanDestinationDir
      - hugo version
